import type { MenuItem } from "@/lib/menu/types";

/**
 * Placeholder menu for UI development. Replace with real data (e.g. Supabase)
 * when your schema is ready.
 */
export const MOCK_MENU_ITEMS: MenuItem[] = [
  {
    id: "mock-1",
    category: "Breakfast",
    name: "Campus breakfast wrap",
    description: "Scrambled egg, cheddar, and spinach in a warm tortilla. Grab before your 9am.",
    price_cents: 599,
    image_url: null,
    is_available: true,
    sort_order: 0,
    iconKey: "wrap",
    created_at: "2026-01-01T12:00:00.000Z",
  },
  {
    id: "mock-2",
    category: "Breakfast",
    name: "Overnight oats",
    description: "Oats with yogurt, honey, and seasonal fruit. Served cold.",
    price_cents: 449,
    image_url: null,
    is_available: true,
    sort_order: 1,
    iconKey: "oats",
    created_at: "2026-01-01T12:00:00.000Z",
  },
  {
    id: "mock-3",
    category: "Breakfast",
    name: "Avocado toast",
    description: "Sourdough, smashed avocado, chili flakes, and lime. Add poached egg at the counter.",
    price_cents: 749,
    image_url: null,
    is_available: false,
    sort_order: 2,
    iconKey: "toast",
    created_at: "2026-01-01T12:00:00.000Z",
  },
  {
    id: "mock-4",
    category: "Mains",
    name: "Campus bowl",
    description: "Rice, seasonal veg, and your choice of protein. A reliable between-classes meal.",
    price_cents: 899,
    image_url: null,
    is_available: true,
    sort_order: 0,
    iconKey: "bowl",
    created_at: "2026-01-01T12:00:00.000Z",
  },
  {
    id: "mock-5",
    category: "Mains",
    name: "Grilled sandwich",
    description: "Toasted sourdough with cheese and greens. Add hot sauce at the counter.",
    price_cents: 649,
    image_url: null,
    is_available: true,
    sort_order: 1,
    iconKey: "sandwich",
    created_at: "2026-01-01T12:00:00.000Z",
  },
  {
    id: "mock-6",
    category: "Mains",
    name: "Tomato basil pasta",
    description: "Penne in a slow-cooked tomato sauce with fresh basil and parmesan.",
    price_cents: 799,
    image_url: null,
    is_available: true,
    sort_order: 2,
    iconKey: "pasta",
    created_at: "2026-01-01T12:00:00.000Z",
  },
  {
    id: "mock-7",
    category: "Mains",
    name: "Chicken teriyaki plate",
    description: "Grilled chicken thigh, steamed broccoli, and jasmine rice with house teriyaki.",
    price_cents: 1099,
    image_url: null,
    is_available: true,
    sort_order: 3,
    iconKey: "chicken",
    created_at: "2026-01-01T12:00:00.000Z",
  },
  {
    id: "mock-8",
    category: "Mains",
    name: "Veggie burger",
    description: "House-made patty, lettuce, tomato, pickles, and vegan mayo on a brioche bun.",
    price_cents: 949,
    image_url: null,
    is_available: true,
    sort_order: 4,
    iconKey: "burger",
    created_at: "2026-01-01T12:00:00.000Z",
  },
  {
    id: "mock-9",
    category: "Mains",
    name: "Soup of the day",
    description: "Rotates daily—ask staff or check the chalkboard near the register.",
    price_cents: 499,
    image_url: null,
    is_available: false,
    sort_order: 5,
    iconKey: "soup",
    created_at: "2026-01-01T12:00:00.000Z",
  },
  {
    id: "mock-10",
    category: "Snacks",
    name: "Fresh fruit cup",
    description: "Melon, berries, and citrus when in season.",
    price_cents: 399,
    image_url: null,
    is_available: true,
    sort_order: 0,
    iconKey: "fruit",
    created_at: "2026-01-01T12:00:00.000Z",
  },
  {
    id: "mock-11",
    category: "Snacks",
    name: "Hummus and pita",
    description: "Classic chickpea dip with warm pita wedges and cucumber sticks.",
    price_cents: 549,
    image_url: null,
    is_available: true,
    sort_order: 1,
    iconKey: "hummus",
    created_at: "2026-01-01T12:00:00.000Z",
  },
  {
    id: "mock-12",
    category: "Snacks",
    name: "Trail mix cup",
    description: "Almonds, cashews, dried cranberries, and dark chocolate chips.",
    price_cents: 349,
    image_url: null,
    is_available: true,
    sort_order: 2,
    iconKey: "trail",
    created_at: "2026-01-01T12:00:00.000Z",
  },
  {
    id: "mock-13",
    category: "Snacks",
    name: "Greek yogurt parfait",
    description: "Layered yogurt, granola, and berry compote in a cup.",
    price_cents: 479,
    image_url: null,
    is_available: true,
    sort_order: 3,
    iconKey: "parfait",
    created_at: "2026-01-01T12:00:00.000Z",
  },
  {
    id: "mock-14",
    category: "Snacks",
    name: "Soft pretzel",
    description: "Warm pretzel with coarse salt. Mustard on the side.",
    price_cents: 329,
    image_url: null,
    is_available: false,
    sort_order: 4,
    iconKey: "pretzel",
    created_at: "2026-01-01T12:00:00.000Z",
  },
  {
    id: "mock-15",
    category: "Drinks",
    name: "Cold brew",
    description: "Slow-steeped coffee. Iced or black.",
    price_cents: 449,
    image_url: null,
    is_available: false,
    sort_order: 0,
    iconKey: "coldbrew",
    created_at: "2026-01-01T12:00:00.000Z",
  },
  {
    id: "mock-16",
    category: "Drinks",
    name: "House lemonade",
    description: "Fresh-squeezed lemons, a touch of mint, served over ice.",
    price_cents: 379,
    image_url: null,
    is_available: true,
    sort_order: 1,
    iconKey: "lemonade",
    created_at: "2026-01-01T12:00:00.000Z",
  },
  {
    id: "mock-17",
    category: "Drinks",
    name: "Sparkling water",
    description: "Chilled cans—lime or plain.",
    price_cents: 199,
    image_url: null,
    is_available: true,
    sort_order: 2,
    iconKey: "water",
    created_at: "2026-01-01T12:00:00.000Z",
  },
  {
    id: "mock-18",
    category: "Drinks",
    name: "Chai latte",
    description: "Spiced black tea with steamed milk. Hot or iced.",
    price_cents: 459,
    image_url: null,
    is_available: true,
    sort_order: 3,
    iconKey: "chai",
    created_at: "2026-01-01T12:00:00.000Z",
  },
  {
    id: "mock-19",
    category: "Drinks",
    name: "Berry smoothie",
    description: "Blended mixed berries, banana, and oat milk.",
    price_cents: 629,
    image_url: null,
    is_available: true,
    sort_order: 4,
    iconKey: "smoothie",
    created_at: "2026-01-01T12:00:00.000Z",
  },
  {
    id: "mock-20",
    category: "Desserts",
    name: "Brownie square",
    description: "Dense chocolate brownie with walnuts. Warm on request.",
    price_cents: 349,
    image_url: null,
    is_available: true,
    sort_order: 0,
    iconKey: "brownie",
    created_at: "2026-01-01T12:00:00.000Z",
  },
  {
    id: "mock-21",
    category: "Desserts",
    name: "Oatmeal cookie",
    description: "Two large cookies—chewy center, crisp edge.",
    price_cents: 249,
    image_url: null,
    is_available: true,
    sort_order: 1,
    iconKey: "cookie",
    created_at: "2026-01-01T12:00:00.000Z",
  },
  {
    id: "mock-22",
    category: "Desserts",
    name: "Seasonal fruit tart",
    description: "Buttery shell with vanilla custard and glazed fruit.",
    price_cents: 549,
    image_url: null,
    is_available: true,
    sort_order: 2,
    iconKey: "tart",
    created_at: "2026-01-01T12:00:00.000Z",
  },
  {
    id: "mock-23",
    category: "Desserts",
    name: "Frozen yogurt cup",
    description: "Self-serve style cup—toppings priced separately at checkout.",
    price_cents: 429,
    image_url: null,
    is_available: false,
    sort_order: 3,
    iconKey: "yogurt",
    created_at: "2026-01-01T12:00:00.000Z",
  },
];
